"""empty message

Revision ID: 3c9fd40467d0
Revises: 9975799c2b8
Create Date: 2014-08-07 22:12:50.244824

"""

# revision identifiers, used by Alembic.
revision = '3c9fd40467d0'
down_revision = '9975799c2b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'group', sa.Column(
        'status_id',
        sa.Integer(),
        server_default='1',
        nullable=False)
    )
    op.create_unique_constraint('_group_user_uc', 'membership', ['user_id', 'group_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_group_user_uc', 'membership')
    op.drop_column(u'group', 'status_id')
    op.drop_table('group_status')
    ### end Alembic commands ###
